import { expect, test } from "@playwright/test";
import path from "path";
import type { ToolResponse } from "../../src/shared/types";
import {
  cleanupAllOpenDocuments,
  cleanupFixtureDir,
  createFixtureDir,
  McpTestClient,
  switchToAnnotationsTab,
} from "./helpers";

/**
 * E2E coverage for AR5-T4 (#945) — .docx reviewer-comment batch-promote.
 *
 * The full flow already exists in master: `.docx` reviewer comments import as
 * **private notes** (`author: "import"`, `type: "note"`, `audience: "private"`)
 * that Claude cannot see; the user selects them in the rail and promotes them
 * to Claude-visible comments via `BatchPromoteBar`. This spec drives that flow
 * through a real browser against a committed binary `.docx` fixture
 * (`tests/e2e/fixtures/reviewer-comments.docx`, regenerated by
 * `scripts/fixtures/make-reviewer-docx.mjs`).
 *
 * Privacy boundary asserted (ADR-027): before promotion the imports are NOT in
 * `tandem_getAnnotations` and are reported under `notesExcluded`. After
 * promotion they appear as `type: "comment"`, `audience: "outbound"`,
 * Claude-visible.
 *
 * Flake mitigation: `.docx` import is heavier than markdown opens, so the spec
 * uses a 60s timeout and a SELECTOR-based retry on the open (re-issues
 * `tandem_open` up to 3x until the per-card checkboxes appear). No fixed-time
 * sleeps. If worker-thread import proves unavoidably flaky in CI, the
 * deterministic AR5-T3 integration test remains the gate-satisfying coverage.
 */

test.setTimeout(60_000);

let mcp: McpTestClient;
let tmpDir: string;

const DOCX_FIXTURE = "reviewer-comments.docx";

/** Shape of the `tandem_getAnnotations` success payload we assert on. */
type GetAnnotationsData = {
  annotations: Array<{
    id: string;
    author: string;
    type: string;
    audience?: string;
  }>;
  count: number;
  notesExcluded?: number;
};

async function getAnnotations(documentId?: string): Promise<GetAnnotationsData> {
  const resp = (await mcp.callTool(
    "tandem_getAnnotations",
    documentId ? { documentId } : {},
  )) as ToolResponse<GetAnnotationsData>;
  if (resp.error !== false) throw new Error("tandem_getAnnotations returned an error envelope");
  return resp.data;
}

test.beforeEach(async () => {
  mcp = new McpTestClient();
  await mcp.connect();
  tmpDir = createFixtureDir(DOCX_FIXTURE);
});

test.afterEach(async () => {
  await cleanupAllOpenDocuments(mcp);
  await mcp.close();
  cleanupFixtureDir(tmpDir);
});

test("docx reviewer comments import as private notes, then batch-promote to Claude-visible comments", async ({
  page,
}) => {
  const filePath = path.join(tmpDir, DOCX_FIXTURE);

  // Open the .docx via the file-open flow, then load the editor. Retry the open
  // up to 3x, gating on the per-card checkboxes appearing — the .docx import is
  // worker/parse-heavy and can lag the first connection. Selector-based, no sleeps.
  // The locator is lazy, so a single instance re-evaluates on each assertion.
  const checkboxes = page.locator("[data-testid^='annotation-select-checkbox-']");
  for (let attempt = 1; attempt <= 3; attempt++) {
    await mcp.callTool("tandem_open", { filePath });
    if (attempt === 1) await page.goto("/");
    await switchToAnnotationsTab(page);
    try {
      await expect(checkboxes).toHaveCount(2, { timeout: 15_000 });
      break;
    } catch (err) {
      // Re-issue the open on the next iteration; surface the failure on the last.
      if (attempt === 3) throw err;
    }
  }

  // The imported reviewer attribution byline should render on each card.
  const bylines = page.locator("[data-testid^='annotation-import-byline-']");
  await expect(bylines).toHaveCount(2);
  await expect(bylines.first()).toContainText("Reviewer1");

  // --- Privacy boundary (ADR-027): imports are private notes, hidden from Claude.
  const before = await getAnnotations();
  // No imported comment is visible to Claude yet — they are all notes.
  expect(before.annotations.some((a) => a.author === "import")).toBe(false);
  expect(before.annotations.filter((a) => a.type === "comment").length).toBe(0);
  // notesExcluded reports the two not-yet-promoted imports.
  expect(before.notesExcluded ?? 0).toBe(2);

  // --- Select both imported notes via the per-card checkboxes.
  const count = await checkboxes.count();
  for (let i = 0; i < count; i++) {
    await checkboxes.nth(i).check();
  }

  // The batch-promote bar appears and reflects the selection count.
  const bar = page.locator("[data-testid='batch-promote-bar']");
  await expect(bar).toBeVisible();
  await expect(page.locator("[data-testid='batch-promote-count']")).toContainText("2 selected");
  const confirm = page.locator("[data-testid='batch-promote-confirm']");
  // Agent-agnostic label (#438): the button reads "Send N to {agentLabel.family}"
  // (e.g. "Assistant" fallback), not a hardcoded "Claude".
  await expect(confirm).toContainText("Send 2 to");

  // --- Promote.
  await confirm.click();

  // The bar clears once the selection is promoted.
  await expect(bar).toHaveCount(0, { timeout: 5_000 });

  // --- Verify via MCP: the promoted annotations are now Claude-visible comments.
  await expect
    .poll(
      async () => {
        const data = await getAnnotations();
        return data.annotations.filter(
          (a) => a.type === "comment" && a.author === "user" && a.audience === "outbound",
        ).length;
      },
      { timeout: 10_000 },
    )
    .toBe(2);

  const after = await getAnnotations();
  // No notes remain excluded — both imports were promoted.
  expect(after.notesExcluded ?? 0).toBe(0);
  // And the promoted comments are present in Claude's view.
  expect(after.count).toBe(2);
});
